const stations = [{ fullname: 'Abbey Road DLR Station', name: 'Abbey Road', mininame: 'Abbey...', longitude: 0.003737, latitude: 51.531926, pinkreader: false, lines: 'DLR', zone: '2/3' },
{ fullname: 'Acton Central Rail Station', name: 'Acton Central', mininame: 'Acton...', longitude: -0.262971, latitude: 51.508716, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'Acton Town Underground Station', name: 'Acton Town', mininame: 'Acton...', longitude: -0.280462, latitude: 51.503057, pinkreader: false, lines: 'District, Piccadilly', zone: '3' },
{ fullname: 'Aldgate East Underground Station', name: 'Aldgate East', mininame: 'Aldga...', longitude: -0.072384, latitude: 51.515037, pinkreader: false, lines: 'District, Hammersmith & City', zone: '1' },
{ fullname: 'Aldgate Underground Station', name: 'Aldgate', mininame: 'Aldga...', longitude: -0.075689, latitude: 51.514246, pinkreader: false, lines: 'Circle, Metropolitan', zone: '1' },
{ fullname: 'All Saints DLR Station', name: 'All Saints', mininame: 'All S...', longitude: -0.013135, latitude: 51.511, pinkreader: false, lines: 'DLR', zone: '2' },
{ fullname: 'Alperton Underground Station', name: 'Alperton', mininame: 'Alper...', longitude: -0.29961, latitude: 51.540627, pinkreader: false, lines: 'Piccadilly', zone: '4' },
{ fullname: 'Amersham Underground Station', name: 'Amersham', mininame: 'Amers...', longitude: -0.607714, latitude: 51.674126, pinkreader: false, lines: 'Metropolitan', zone: '9' },
{ fullname: 'Anerley Rail Station', name: 'Anerley', mininame: 'Anerl...', longitude: -0.065886, latitude: 51.412153, pinkreader: false, lines: 'London Overground', zone: '4' },
{ fullname: 'Angel Underground Station', name: 'Angel', mininame: 'Angel...', longitude: -0.105992, latitude: 51.532796, pinkreader: false, lines: 'Northern', zone: '1' },
{ fullname: 'Archway Underground Station', name: 'Archway', mininame: 'Archw...', longitude: -0.134819, latitude: 51.565478, pinkreader: false, lines: 'Northern', zone: '2+3' },
{ fullname: 'Arnos Grove Underground Station', name: 'Arnos Grove', mininame: 'Arnos...', longitude: -0.133062, latitude: 51.616446, pinkreader: false, lines: 'Piccadilly', zone: '4' },
{ fullname: 'Arsenal Underground Station', name: 'Arsenal', mininame: 'Arsen...', longitude: -0.107457, latitude: 51.558655, pinkreader: false, lines: 'Piccadilly', zone: '2' },
{ fullname: 'Baker Street Underground Station', name: 'Baker Street', mininame: 'Baker...', longitude: -0.15713, latitude: 51.522883, pinkreader: false, lines: 'Bakerloo, Circle, Hammersmith & City, Jubilee, Metropolitan', zone: '1' },
{ fullname: 'Balham Underground Station', name: 'Balham', mininame: 'Balha...', longitude: -0.152997, latitude: 51.443288, pinkreader: false, lines: 'Northern', zone: '3' },
{ fullname: 'Bank DLR Station', name: 'Bank', mininame: 'Bank ...', longitude: -0.088515, latitude: 51.513233, pinkreader: false, lines: 'DLR', zone: '1' },
{ fullname: 'Bank Underground Station', name: 'Bank', mininame: 'Bank ...', longitude: -0.088204, latitude: 51.512751, pinkreader: false, lines: 'Central, Northern, Waterloo & City', zone: '1' },
{ fullname: 'Barbican Underground Station', name: 'Barbican', mininame: 'Barbi...', longitude: -0.097993, latitude: 51.520275, pinkreader: false, lines: 'Circle, Hammersmith & City, Metropolitan', zone: '1' },
{ fullname: 'Barking Rail Station', name: 'Barking', mininame: 'Barki...', longitude: 0.080903, latitude: 51.539495, pinkreader: false, lines: 'London Overground', zone: '4' },
{ fullname: 'Barking Underground Station', name: 'Barking', mininame: 'Barki...', longitude: 0.081053, latitude: 51.539321, pinkreader: false, lines: 'District, Hammersmith & City', zone: '4' },
{ fullname: 'Barkingside Underground Station', name: 'Barkingside', mininame: 'Barki...', longitude: 0.088585, latitude: 51.585689, pinkreader: false, lines: 'Central', zone: '4' },
{ fullname: 'Barons Court Underground Station', name: 'Barons Court', mininame: 'Baron...', longitude: -0.213427, latitude: 51.490311, pinkreader: false, lines: 'District, Piccadilly', zone: '2' },
{ fullname: 'Bayswater Underground Station', name: 'Bayswater', mininame: 'Baysw...', longitude: -0.187938, latitude: 51.512284, pinkreader: false, lines: 'Circle, District', zone: '1' },
{ fullname: 'Beckton DLR Station', name: 'Beckton', mininame: 'Beckt...', longitude: 0.061453, latitude: 51.514362, pinkreader: false, lines: 'DLR', zone: '3' },
{ fullname: 'Beckton Park DLR Station', name: 'Beckton Park', mininame: 'Beckt...', longitude: 0.054932, latitude: 51.508793, pinkreader: false, lines: 'DLR', zone: '3' },
{ fullname: 'Becontree Underground Station', name: 'Becontree', mininame: 'Becon...', longitude: 0.127016, latitude: 51.540331, pinkreader: false, lines: 'District', zone: '5' },
{ fullname: 'Belsize Park Underground Station', name: 'Belsize Park', mininame: 'Belsi...', longitude: -0.164648, latitude: 51.550311, pinkreader: false, lines: 'Northern', zone: '2' },
{ fullname: 'Bermondsey Underground Station', name: 'Bermondsey', mininame: 'Bermo...', longitude: -0.063769, latitude: 51.497953, pinkreader: false, lines: 'Jubilee', zone: '2' },
{ fullname: 'Bethnal Green Rail Station', name: 'Bethnal Green', mininame: 'Bethn...', longitude: -0.059568, latitude: 51.523917, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Bethnal Green Underground Station', name: 'Bethnal Green', mininame: 'Bethn...', longitude: -0.055506, latitude: 51.527222, pinkreader: false, lines: 'Central', zone: '2' },
{ fullname: 'Blackfriars Underground Station', name: 'Blackfriars', mininame: 'Black...', longitude: -0.103659, latitude: 51.511581, pinkreader: false, lines: 'Circle, District', zone: '1' },
{ fullname: 'Blackhorse Road Rail Station', name: 'Blackhorse Road', mininame: 'Black...', longitude: -0.041236, latitude: 51.586605, pinkreader: true, lines: 'London Overground', zone: '3' },
{ fullname: 'Blackhorse Road Underground Station', name: 'Blackhorse Road', mininame: 'Black...', longitude: -0.04115, latitude: 51.586919, pinkreader: false, lines: 'Victoria', zone: '3' },
{ fullname: 'Blackwall DLR Station', name: 'Blackwall', mininame: 'Black...', longitude: -0.006969, latitude: 51.507991, pinkreader: false, lines: 'DLR', zone: '2' },
{ fullname: 'Bond Street Underground Station', name: 'Bond Street', mininame: 'Bond ...', longitude: -0.149723, latitude: 51.514304, pinkreader: false, lines: 'Central, Jubilee', zone: '1' },
{ fullname: 'Borough Underground Station', name: 'Borough', mininame: 'Borou...', longitude: -0.09337, latitude: 51.501199, pinkreader: false, lines: 'Northern', zone: '1' },
{ fullname: 'Boston Manor Underground Station', name: 'Boston Manor', mininame: 'Bosto...', longitude: -0.324939, latitude: 51.495635, pinkreader: false, lines: 'Piccadilly', zone: '4' },
{ fullname: 'Bounds Green Underground Station', name: 'Bounds Green', mininame: 'Bound...', longitude: -0.124235, latitude: 51.607034, pinkreader: false, lines: 'Piccadilly', zone: '3+4' },
{ fullname: 'Bow Church DLR Station', name: 'Bow Church', mininame: 'Bow C...', longitude: -0.020936, latitude: 51.527858, pinkreader: false, lines: 'DLR', zone: '2' },
{ fullname: 'Bow Road Underground Station', name: 'Bow Road', mininame: 'Bow R...', longitude: -0.025128, latitude: 51.52694, pinkreader: false, lines: 'District, Hammersmith & City', zone: '2' },
{ fullname: 'Brent Cross Underground Station', name: 'Brent Cross', mininame: 'Brent...', longitude: -0.213622, latitude: 51.57665, pinkreader: false, lines: 'Northern', zone: '3' },
{ fullname: 'Brixton Underground Station', name: 'Brixton', mininame: 'Brixt...', longitude: -0.114888, latitude: 51.462618, pinkreader: false, lines: 'Victoria', zone: '2' },
{ fullname: 'Brockley Rail Station', name: 'Brockley', mininame: 'Brock...', longitude: -0.037537, latitude: 51.464649, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Bromley-by-Bow Underground Station', name: 'Bromley-by-Bow', mininame: 'Broml...', longitude: -0.011538, latitude: 51.524839, pinkreader: false, lines: 'District, Hammersmith & City', zone: '2+3' },
{ fullname: 'Brondesbury Park Rail Station', name: 'Brondesbury Park', mininame: 'Brond...', longitude: -0.210128, latitude: 51.540699, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Brondesbury Rail Station', name: 'Brondesbury', mininame: 'Brond...', longitude: -0.202309, latitude: 51.545166, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Bruce Grove Rail Station', name: 'Bruce Grove', mininame: 'Bruce...', longitude: -0.069867, latitude: 51.593959, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'Buckhurst Hill Underground Station', name: 'Buckhurst Hill', mininame: 'Buckh...', longitude: 0.046757, latitude: 51.626605, pinkreader: false, lines: 'Central', zone: '5' },
{ fullname: 'Burnt Oak Underground Station', name: 'Burnt Oak', mininame: 'Burnt...', longitude: -0.264048, latitude: 51.602774, pinkreader: false, lines: 'Northern', zone: '4' },
{ fullname: 'Bush Hill Park Rail Station', name: 'Bush Hill Park', mininame: 'Bush ...', longitude: -0.069221, latitude: 51.641519, pinkreader: false, lines: 'London Overground', zone: '5' },
{ fullname: 'Bushey Rail Station', name: 'Bushey', mininame: 'Bushe...', longitude: -0.384749, latitude: 51.645582, pinkreader: false, lines: 'London Overground', zone: '8' },
{ fullname: 'Caledonian Road & Barnsbury Rail Station', name: 'Caledonian Road & Barnsbury', mininame: 'Caled...', longitude: -0.116729, latitude: 51.543041, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Caledonian Road Underground Station', name: 'Caledonian Road', mininame: 'Caled...', longitude: -0.118493, latitude: 51.548519, pinkreader: false, lines: 'Piccadilly', zone: '2' },
{ fullname: 'Cambridge Heath (London) Rail Station', name: 'Cambridge Heath (London)', mininame: 'Cambr...', longitude: -0.057279, latitude: 51.531973, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Camden Road Rail Station', name: 'Camden Road', mininame: 'Camde...', longitude: -0.138701, latitude: 51.541791, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Camden Town Underground Station', name: 'Camden Town', mininame: 'Camde...', longitude: -0.14274, latitude: 51.539292, pinkreader: false, lines: 'Northern', zone: '2' },
{ fullname: 'Canada Water Rail Station', name: 'Canada Water', mininame: 'Canad...', longitude: -0.04972, latitude: 51.49799, pinkreader: true, lines: 'London Overground', zone: '2' },
{ fullname: 'Canada Water Underground Station', name: 'Canada Water', mininame: 'Canad...', longitude: -0.049722, latitude: 51.497945, pinkreader: false, lines: 'Jubilee', zone: '2' },
{ fullname: 'Canary Wharf DLR Station', name: 'Canary Wharf', mininame: 'Canar...', longitude: -0.020997, latitude: 51.504838, pinkreader: false, lines: 'DLR', zone: '2' },
{ fullname: 'Canary Wharf Underground Station', name: 'Canary Wharf', mininame: 'Canar...', longitude: -0.018246, latitude: 51.503488, pinkreader: false, lines: 'Jubilee', zone: '2' },
{ fullname: 'Canning Town DLR Station', name: 'Canning Town', mininame: 'Canni...', longitude: 0.008101, latitude: 51.514127, pinkreader: false, lines: 'DLR', zone: '2/3' },
{ fullname: 'Canning Town Underground Station', name: 'Canning Town', mininame: 'Canni...', longitude: 0.008322, latitude: 51.513584, pinkreader: false, lines: 'Jubilee', zone: '2/3' },
{ fullname: 'Cannon Street Underground Station', name: 'Cannon Street', mininame: 'Canno...', longitude: -0.090432, latitude: 51.51151, pinkreader: false, lines: 'Circle, District', zone: '1' },
{ fullname: 'Canonbury Rail Station', name: 'Canonbury', mininame: 'Canon...', longitude: -0.092191, latitude: 51.548732, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Canons Park Underground Station', name: 'Canons Park', mininame: 'Canon...', longitude: -0.294693, latitude: 51.607701, pinkreader: false, lines: 'Jubilee', zone: '5' },
{ fullname: 'Carpenders Park Rail Station', name: 'Carpenders Park', mininame: 'Carpe...', longitude: -0.385939, latitude: 51.628351, pinkreader: false, lines: 'London Overground', zone: '7' },
{ fullname: 'Chalfont & Latimer Underground Station', name: 'Chalfont & Latimer', mininame: 'Chalf...', longitude: -0.560689, latitude: 51.667985, pinkreader: false, lines: 'Metropolitan', zone: '8' },
{ fullname: 'Chalk Farm Underground Station', name: 'Chalk Farm', mininame: 'Chalk...', longitude: -0.153388, latitude: 51.544118, pinkreader: false, lines: 'Northern', zone: '2' },
{ fullname: 'Chancery Lane Underground Station', name: 'Chancery Lane', mininame: 'Chanc...', longitude: -0.111583, latitude: 51.518247, pinkreader: false, lines: 'Central', zone: '1' },
{ fullname: 'Charing Cross Underground Station', name: 'Charing Cross', mininame: 'Chari...', longitude: -0.127277, latitude: 51.50741, pinkreader: false, lines: 'Bakerloo, Northern', zone: '1' },
{ fullname: 'Chesham Underground Station', name: 'Chesham', mininame: 'Chesh...', longitude: -0.611247, latitude: 51.705208, pinkreader: false, lines: 'Metropolitan', zone: '9' },
{ fullname: 'Cheshunt Rail Station', name: 'Cheshunt', mininame: 'Chesh...', longitude: -0.02396, latitude: 51.702876, pinkreader: false, lines: 'London Overground', zone: '8' },
{ fullname: 'Chigwell Underground Station', name: 'Chigwell', mininame: 'Chigw...', longitude: 0.075041, latitude: 51.617916, pinkreader: false, lines: 'Central', zone: '4' },
{ fullname: 'Chingford Rail Station', name: 'Chingford', mininame: 'Ching...', longitude: 0.009897, latitude: 51.633087, pinkreader: false, lines: 'London Overground', zone: '5' },
{ fullname: 'Chiswick Park Underground Station', name: 'Chiswick Park', mininame: 'Chisw...', longitude: -0.267972, latitude: 51.494627, pinkreader: false, lines: 'District, Piccadilly', zone: '3' },
{ fullname: 'Chorleywood Underground Station', name: 'Chorleywood', mininame: 'Chorl...', longitude: -0.518461, latitude: 51.654358, pinkreader: false, lines: 'Metropolitan', zone: '7' },
{ fullname: 'Clapham Common Underground Station', name: 'Clapham Common', mininame: 'Claph...', longitude: -0.138317, latitude: 51.461742, pinkreader: false, lines: 'Northern', zone: '2' },
{ fullname: 'Clapham High Street Rail Station', name: 'Clapham High Street', mininame: 'Claph...', longitude: -0.132522, latitude: 51.465481, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Clapham Junction Rail Station', name: 'Clapham Junction', mininame: 'Claph...', longitude: -0.170221, latitude: 51.464187, pinkreader: true, lines: 'London Overground', zone: 'zone data for this station unavailable from tfl data' },
{ fullname: 'Clapham North Underground Station', name: 'Clapham North', mininame: 'Claph...', longitude: -0.130016, latitude: 51.465135, pinkreader: false, lines: 'Northern', zone: '2' },
{ fullname: 'Clapham South Underground Station', name: 'Clapham South', mininame: 'Claph...', longitude: -0.147582, latitude: 51.452654, pinkreader: false, lines: 'Northern', zone: '2+3' },
{ fullname: 'Clapton Rail Station', name: 'Clapton', mininame: 'Clapt...', longitude: -0.057025, latitude: 51.561644, pinkreader: false, lines: 'London Overground', zone: '2+3' },
{ fullname: 'Cockfosters Underground Station', name: 'Cockfosters', mininame: 'Cockf...', longitude: -0.149171, latitude: 51.65152, pinkreader: false, lines: 'Piccadilly', zone: '5' },
{ fullname: 'Colindale Underground Station', name: 'Colindale', mininame: 'Colin...', longitude: -0.249919, latitude: 51.595424, pinkreader: false, lines: 'Northern', zone: '4' },
{ fullname: 'Colliers Wood Underground Station', name: 'Colliers Wood', mininame: 'Colli...', longitude: -0.178086, latitude: 51.41816, pinkreader: false, lines: 'Northern', zone: '3' },
{ fullname: 'Covent Garden Underground Station', name: 'Covent Garden', mininame: 'Coven...', longitude: -0.124436, latitude: 51.513093, pinkreader: false, lines: 'Piccadilly', zone: '1' },
{ fullname: 'Crossharbour DLR Station', name: 'Crossharbour', mininame: 'Cross...', longitude: -0.014606, latitude: 51.495728, pinkreader: false, lines: 'DLR', zone: '2' },
{ fullname: 'Crouch Hill Rail Station', name: 'Crouch Hill', mininame: 'Crouc...', longitude: -0.117149, latitude: 51.571302, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'Croxley Underground Station', name: 'Croxley', mininame: 'Croxl...', longitude: -0.441718, latitude: 51.647044, pinkreader: false, lines: 'Metropolitan', zone: '7' },
{ fullname: 'Crystal Palace Rail Station', name: 'Crystal Palace', mininame: 'Cryst...', longitude: -0.07261, latitude: 51.418109, pinkreader: false, lines: 'London Overground', zone: '3+4' },
{ fullname: 'Custom House (for ExCel) DLR Station', name: 'Custom House (for ExCel)', mininame: 'Custo...', longitude: 0.026699, latitude: 51.509716, pinkreader: false, lines: 'DLR', zone: '3' },
{ fullname: 'Cutty Sark (for Maritime Greenwich) DLR Station', name: 'Cutty Sark (for Maritime Greenwich)', mininame: 'Cutty...', longitude: -0.01081, latitude: 51.481671, pinkreader: false, lines: 'DLR', zone: '2+3' },
{ fullname: 'Cyprus DLR Station', name: 'Cyprus', mininame: 'Cypru...', longitude: 0.063925, latitude: 51.508473, pinkreader: false, lines: 'DLR', zone: '3' },
{ fullname: 'Dagenham East Underground Station', name: 'Dagenham East', mininame: 'Dagen...', longitude: 0.166017, latitude: 51.544096, pinkreader: false, lines: 'District', zone: '5' },
{ fullname: 'Dagenham Heathway Underground Station', name: 'Dagenham Heathway', mininame: 'Dagen...', longitude: 0.147527, latitude: 51.541639, pinkreader: false, lines: 'District', zone: '5' },
{ fullname: 'Dalston Junction Rail Station', name: 'Dalston Junction', mininame: 'Dalst...', longitude: -0.075137, latitude: 51.546116, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Dalston Kingsland Rail Station', name: 'Dalston Kingsland', mininame: 'Dalst...', longitude: -0.075701, latitude: 51.548148, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Debden Underground Station', name: 'Debden', mininame: 'Debde...', longitude: 0.083782, latitude: 51.645386, pinkreader: false, lines: 'Central', zone: '6' },
{ fullname: 'Denmark Hill Rail Station', name: 'Denmark Hill', mininame: 'Denma...', longitude: -0.089361, latitude: 51.468203, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Deptford Bridge DLR Station', name: 'Deptford Bridge', mininame: 'Deptf...', longitude: -0.022438, latitude: 51.474215, pinkreader: false, lines: 'DLR', zone: '2+3' },
{ fullname: 'Devons Road DLR Station', name: 'Devons Road', mininame: 'Devon...', longitude: -0.017615, latitude: 51.522667, pinkreader: false, lines: 'DLR', zone: '2' },
{ fullname: 'Dollis Hill Underground Station', name: 'Dollis Hill', mininame: 'Dolli...', longitude: -0.239068, latitude: 51.551955, pinkreader: false, lines: 'Jubilee', zone: '3' },
{ fullname: 'Ealing Broadway Underground Station', name: 'Ealing Broadway', mininame: 'Ealin...', longitude: -0.301457, latitude: 51.515017, pinkreader: false, lines: 'Central, District', zone: '3' },
{ fullname: 'Ealing Common Underground Station', name: 'Ealing Common', mininame: 'Ealin...', longitude: -0.288265, latitude: 51.51014, pinkreader: false, lines: 'District, Piccadilly', zone: '3' },
{ fullname: 'Earl&#39;s Court Underground Station', name: 'Earl&#39;s Court', mininame: 'Earl&...', longitude: -0.193378, latitude: 51.492063, pinkreader: false, lines: 'District, Piccadilly', zone: '1+2' },
{ fullname: 'East Acton Underground Station', name: 'East Acton', mininame: 'East ...', longitude: -0.247248, latitude: 51.516612, pinkreader: false, lines: 'Central', zone: '2' },
{ fullname: 'East Finchley Underground Station', name: 'East Finchley', mininame: 'East ...', longitude: -0.165012, latitude: 51.587131, pinkreader: false, lines: 'Northern', zone: '3' },
{ fullname: 'East Ham Underground Station', name: 'East Ham', mininame: 'East ...', longitude: 0.051186, latitude: 51.538948, pinkreader: false, lines: 'District, Hammersmith & City', zone: '3+4' },
{ fullname: 'East India DLR Station', name: 'East India', mininame: 'East ...', longitude: -0.002326, latitude: 51.509359, pinkreader: false, lines: 'DLR', zone: '2+3' },
{ fullname: 'East Putney Underground Station', name: 'East Putney', mininame: 'East ...', longitude: -0.211, latitude: 51.459205, pinkreader: false, lines: 'District', zone: '2+3' },
{ fullname: 'Eastcote Underground Station', name: 'Eastcote', mininame: 'Eastc...', longitude: -0.397373, latitude: 51.576506, pinkreader: false, lines: 'Metropolitan, Piccadilly', zone: '5' },
{ fullname: 'Edgware Road (Bakerloo) Underground Station', name: 'Edgware Road (Bakerloo)', mininame: 'Edgwa...', longitude: -0.17015, latitude: 51.520299, pinkreader: false, lines: 'Bakerloo', zone: '1' },
{ fullname: 'Edgware Road (Circle Line) Underground Station', name: 'Edgware Road (Circle Line)', mininame: 'Edgwa...', longitude: -0.167832, latitude: 51.519858, pinkreader: false, lines: 'Circle, District, Hammersmith & City', zone: '1' },
{ fullname: 'Edgware Underground Station', name: 'Edgware', mininame: 'Edgwa...', longitude: -0.274928, latitude: 51.613653, pinkreader: false, lines: 'Northern', zone: '5' },
{ fullname: 'Edmonton Green Rail Station', name: 'Edmonton Green', mininame: 'Edmon...', longitude: -0.061112, latitude: 51.624929, pinkreader: false, lines: 'London Overground', zone: '4' },
{ fullname: 'Elephant & Castle Underground Station', name: 'Elephant & Castle', mininame: 'Eleph...', longitude: -0.100606, latitude: 51.494536, pinkreader: false, lines: 'Bakerloo, Northern', zone: '1+2' },
{ fullname: 'Elm Park Underground Station', name: 'Elm Park', mininame: 'Elm P...', longitude: 0.19864, latitude: 51.549775, pinkreader: false, lines: 'District', zone: '6' },
{ fullname: 'Elverson Road DLR Station', name: 'Elverson Road', mininame: 'Elver...', longitude: -0.016728, latitude: 51.469074, pinkreader: false, lines: 'DLR', zone: '2+3' },
{ fullname: 'Embankment Underground Station', name: 'Embankment', mininame: 'Emban...', longitude: -0.122666, latitude: 51.507058, pinkreader: false, lines: 'Bakerloo, Circle, District, Northern', zone: '1' },
{ fullname: 'Emerson Park Rail Station', name: 'Emerson Park', mininame: 'Emers...', longitude: 0.220113, latitude: 51.568642, pinkreader: false, lines: 'London Overground', zone: '6' },
{ fullname: 'Enfield Town Rail Station', name: 'Enfield Town', mininame: 'Enfie...', longitude: -0.079328, latitude: 51.652026, pinkreader: false, lines: 'London Overground', zone: '5' },
{ fullname: 'Epping Underground Station', name: 'Epping', mininame: 'Eppin...', longitude: 0.113767, latitude: 51.69368, pinkreader: false, lines: 'Central', zone: '6' },
{ fullname: 'Euston Square Underground Station', name: 'Euston Square', mininame: 'Eusto...', longitude: -0.135829, latitude: 51.525604, pinkreader: false, lines: 'Circle, Hammersmith & City, Metropolitan', zone: '1' },
{ fullname: 'Euston Underground Station', name: 'Euston', mininame: 'Eusto...', longitude: -0.1323, latitude: 51.528344, pinkreader: false, lines: 'Northern, Victoria', zone: '1' },
{ fullname: 'Fairlop Underground Station', name: 'Fairlop', mininame: 'Fairl...', longitude: 0.091004, latitude: 51.595618, pinkreader: false, lines: 'Central', zone: '4' },
{ fullname: 'Farringdon Underground Station', name: 'Farringdon', mininame: 'Farri...', longitude: -0.104913, latitude: 51.520252, pinkreader: false, lines: 'Circle, Hammersmith & City, Metropolitan', zone: '1' },
{ fullname: 'Finchley Central Underground Station', name: 'Finchley Central', mininame: 'Finch...', longitude: -0.192527, latitude: 51.600921, pinkreader: false, lines: 'Northern', zone: '4' },
{ fullname: 'Finchley Road & Frognal Rail Station', name: 'Finchley Road & Frognal', mininame: 'Finch...', longitude: -0.183141, latitude: 51.550266, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Finchley Road Underground Station', name: 'Finchley Road', mininame: 'Finch...', longitude: -0.179845, latitude: 51.546825, pinkreader: false, lines: 'Jubilee, Metropolitan', zone: '2' },
{ fullname: 'Finsbury Park Underground Station', name: 'Finsbury Park', mininame: 'Finsb...', longitude: -0.106825, latitude: 51.564158, pinkreader: false, lines: 'Piccadilly, Victoria', zone: '2' },
{ fullname: 'Forest Hill Rail Station', name: 'Forest Hill', mininame: 'Fores...', longitude: -0.053157, latitude: 51.43928, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'Fulham Broadway Underground Station', name: 'Fulham Broadway', mininame: 'Fulha...', longitude: -0.195422, latitude: 51.480081, pinkreader: false, lines: 'District', zone: '2' },
{ fullname: 'Gallions Reach DLR Station', name: 'Gallions Reach', mininame: 'Galli...', longitude: 0.071555, latitude: 51.508941, pinkreader: false, lines: 'DLR', zone: '3' },
{ fullname: 'Gants Hill Underground Station', name: 'Gants Hill', mininame: 'Gants...', longitude: 0.066185, latitude: 51.576544, pinkreader: false, lines: 'Central', zone: '4' },
{ fullname: 'Gloucester Road Underground Station', name: 'Gloucester Road', mininame: 'Glouc...', longitude: -0.182658, latitude: 51.494316, pinkreader: false, lines: 'Circle, District, Piccadilly', zone: '1' },
{ fullname: 'Golders Green Underground Station', name: 'Golders Green', mininame: 'Golde...', longitude: -0.194039, latitude: 51.572259, pinkreader: false, lines: 'Northern', zone: '3' },
{ fullname: 'Goldhawk Road Underground Station', name: 'Goldhawk Road', mininame: 'Goldh...', longitude: -0.226715, latitude: 51.502005, pinkreader: false, lines: 'Circle, Hammersmith & City', zone: '2' },
{ fullname: 'Goodge Street Underground Station', name: 'Goodge Street', mininame: 'Goodg...', longitude: -0.134361, latitude: 51.520599, pinkreader: false, lines: 'Northern', zone: '1' },
{ fullname: 'Gospel Oak Rail Station', name: 'Gospel Oak', mininame: 'Gospe...', longitude: -0.15077, latitude: 51.555335, pinkreader: true, lines: 'London Overground', zone: '2' },
{ fullname: 'Grange Hill Underground Station', name: 'Grange Hill', mininame: 'Grang...', longitude: 0.092066, latitude: 51.613378, pinkreader: false, lines: 'Central', zone: '4' },
{ fullname: 'Great Portland Street Underground Station', name: 'Great Portland Street', mininame: 'Great...', longitude: -0.144262, latitude: 51.52384, pinkreader: false, lines: 'Circle, Hammersmith & City, Metropolitan', zone: '1' },
{ fullname: 'Green Park Underground Station', name: 'Green Park', mininame: 'Green...', longitude: -0.142787, latitude: 51.506947, pinkreader: false, lines: 'Jubilee, Piccadilly, Victoria', zone: '1' },
{ fullname: 'Greenford Underground Station', name: 'Greenford', mininame: 'Green...', longitude: -0.34605, latitude: 51.542424, pinkreader: false, lines: 'Central', zone: '4' },
{ fullname: 'Greenwich DLR Station', name: 'Greenwich', mininame: 'Green...', longitude: -0.013673, latitude: 51.478087, pinkreader: false, lines: 'DLR', zone: '2+3' },
{ fullname: 'Gunnersbury Rail Station', name: 'Gunnersbury', mininame: 'Gunne...', longitude: -0.275286, latitude: 51.491678, pinkreader: true, lines: 'London Overground', zone: '3' },
{ fullname: 'Gunnersbury Underground Station', name: 'Gunnersbury', mininame: 'Gunne...', longitude: -0.275267, latitude: 51.491803, pinkreader: false, lines: 'District', zone: '3' },
{ fullname: 'Hackney Central Rail Station', name: 'Hackney Central', mininame: 'Hackn...', longitude: -0.056058, latitude: 51.547105, pinkreader: true, lines: 'London Overground', zone: '2' },
{ fullname: 'Hackney Downs Rail Station', name: 'Hackney Downs', mininame: 'Hackn...', longitude: -0.060819, latitude: 51.548757, pinkreader: true, lines: 'London Overground', zone: '2' },
{ fullname: 'Hackney Wick Rail Station', name: 'Hackney Wick', mininame: 'Hackn...', longitude: -0.02492, latitude: 51.54341, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Haggerston Rail Station', name: 'Haggerston', mininame: 'Hagge...', longitude: -0.075666, latitude: 51.538705, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Hainault Underground Station', name: 'Hainault', mininame: 'Haina...', longitude: 0.093482, latitude: 51.603659, pinkreader: false, lines: 'Central', zone: '4' },
{ fullname: 'Hammersmith (Dist&Picc Line) Underground Station', name: 'Hammersmith (Dist&Picc Line)', mininame: 'Hamme...', longitude: -0.22362, latitude: 51.4923, pinkreader: false, lines: 'District, Piccadilly', zone: '2' },
{ fullname: 'Hammersmith (H&C Line) Underground Station', name: 'Hammersmith (H&C Line)', mininame: 'Hamme...', longitude: -0.225013, latitude: 51.493535, pinkreader: false, lines: 'Circle, Hammersmith & City', zone: '2' },
{ fullname: 'Hampstead Heath Rail Station', name: 'Hampstead Heath', mininame: 'Hamps...', longitude: -0.165705, latitude: 51.55521, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Hampstead Underground Station', name: 'Hampstead', mininame: 'Hamps...', longitude: -0.178487, latitude: 51.556632, pinkreader: false, lines: 'Northern', zone: '2+3' },
{ fullname: 'Hanger Lane Underground Station', name: 'Hanger Lane', mininame: 'Hange...', longitude: -0.292704, latitude: 51.530177, pinkreader: false, lines: 'Central', zone: '3' },
{ fullname: 'Harlesden Rail Station', name: 'Harlesden', mininame: 'Harle...', longitude: -0.257667, latitude: 51.536289, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'Harlesden Underground Station', name: 'Harlesden', mininame: 'Harle...', longitude: -0.257883, latitude: 51.53631, pinkreader: false, lines: 'Bakerloo', zone: '3' },
{ fullname: 'Harringay Green Lanes Rail Station', name: 'Harringay Green Lanes', mininame: 'Harri...', longitude: -0.098144, latitude: 51.577182, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'Harrow & Wealdstone Rail Station', name: 'Harrow & Wealdstone', mininame: 'Harro...', longitude: -0.334571, latitude: 51.592169, pinkreader: false, lines: 'London Overground', zone: '5' },
{ fullname: 'Harrow & Wealdstone Underground Station', name: 'Harrow & Wealdstone', mininame: 'Harro...', longitude: -0.335217, latitude: 51.592268, pinkreader: false, lines: 'Bakerloo', zone: '5' },
{ fullname: 'Harrow-on-the-Hill Underground Station', name: 'Harrow-on-the-Hill', mininame: 'Harro...', longitude: -0.337225, latitude: 51.579195, pinkreader: false, lines: 'Metropolitan', zone: '5' },
{ fullname: 'Hatch End Rail Station', name: 'Hatch End', mininame: 'Hatch...', longitude: -0.368601, latitude: 51.609417, pinkreader: false, lines: 'London Overground', zone: '6' },
{ fullname: 'Hatton Cross Underground Station', name: 'Hatton Cross', mininame: 'Hatto...', longitude: -0.423191, latitude: 51.466747, pinkreader: false, lines: 'Piccadilly', zone: '5+6' },
{ fullname: 'Headstone Lane Rail Station', name: 'Headstone Lane', mininame: 'Heads...', longitude: -0.35722, latitude: 51.602649, pinkreader: false, lines: 'London Overground', zone: '5' },
{ fullname: 'Heathrow Terminal 4 Underground Station', name: 'Heathrow Terminal 4', mininame: 'Heath...', longitude: -0.445771, latitude: 51.458524, pinkreader: false, lines: 'Piccadilly', zone: '6' },
{ fullname: 'Heathrow Terminal 5 Underground Station', name: 'Heathrow Terminal 5', mininame: 'Heath...', longitude: -0.49056, latitude: 51.470052, pinkreader: false, lines: 'Piccadilly', zone: '6' },
{ fullname: 'Heathrow Terminals 2 & 3 Underground Station', name: 'Heathrow Terminals 2 & 3', mininame: 'Heath...', longitude: -0.452265, latitude: 51.471235, pinkreader: false, lines: 'Piccadilly', zone: '6' },
{ fullname: 'Hendon Central Underground Station', name: 'Hendon Central', mininame: 'Hendo...', longitude: -0.226424, latitude: 51.583301, pinkreader: false, lines: 'Northern', zone: '3+4' },
{ fullname: 'Heron Quays DLR Station', name: 'Heron Quays', mininame: 'Heron...', longitude: -0.021421, latitude: 51.503379, pinkreader: false, lines: 'DLR', zone: '2' },
{ fullname: 'High Barnet Underground Station', name: 'High Barnet', mininame: 'High ...', longitude: -0.194298, latitude: 51.650541, pinkreader: false, lines: 'Northern', zone: '5' },
{ fullname: 'High Street Kensington Underground Station', name: 'High Street Kensington', mininame: 'High ...', longitude: -0.192792, latitude: 51.501055, pinkreader: false, lines: 'Circle, District', zone: '1' },
{ fullname: 'Highams Park Rail Station', name: 'Highams Park', mininame: 'Higha...', longitude: -0.000222, latitude: 51.60835, pinkreader: false, lines: 'London Overground', zone: '4' },
{ fullname: 'Highbury & Islington Rail Station', name: 'Highbury & Islington', mininame: 'Highb...', longitude: -0.103764, latitude: 51.546177, pinkreader: true, lines: 'London Overground', zone: '2' },
{ fullname: 'Highbury & Islington Underground Station', name: 'Highbury & Islington', mininame: 'Highb...', longitude: -0.103324, latitude: 51.54635, pinkreader: false, lines: 'Victoria', zone: '2' },
{ fullname: 'Highgate Underground Station', name: 'Highgate', mininame: 'Highg...', longitude: -0.145857, latitude: 51.577532, pinkreader: false, lines: 'Northern', zone: '3' },
{ fullname: 'Hillingdon Underground Station', name: 'Hillingdon', mininame: 'Hilli...', longitude: -0.449828, latitude: 51.553715, pinkreader: false, lines: 'Metropolitan, Piccadilly', zone: '6' },
{ fullname: 'Holborn Underground Station', name: 'Holborn', mininame: 'Holbo...', longitude: -0.120475, latitude: 51.51758, pinkreader: false, lines: 'Central, Piccadilly', zone: '1' },
{ fullname: 'Holland Park Underground Station', name: 'Holland Park', mininame: 'Holla...', longitude: -0.205679, latitude: 51.507143, pinkreader: false, lines: 'Central', zone: '2' },
{ fullname: 'Holloway Road Underground Station', name: 'Holloway Road', mininame: 'Hollo...', longitude: -0.113244, latitude: 51.552697, pinkreader: false, lines: 'Piccadilly', zone: '2' },
{ fullname: 'Homerton Rail Station', name: 'Homerton', mininame: 'Homer...', longitude: -0.04236, latitude: 51.547012, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Honor Oak Park Rail Station', name: 'Honor Oak Park', mininame: 'Honor...', longitude: -0.045505, latitude: 51.449989, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'Hornchurch Underground Station', name: 'Hornchurch', mininame: 'Hornc...', longitude: 0.219116, latitude: 51.554093, pinkreader: false, lines: 'District', zone: '6' },
{ fullname: 'Hounslow Central Underground Station', name: 'Hounslow Central', mininame: 'Houns...', longitude: -0.366578, latitude: 51.471295, pinkreader: false, lines: 'Piccadilly', zone: '4' },
{ fullname: 'Hounslow East Underground Station', name: 'Hounslow East', mininame: 'Houns...', longitude: -0.356474, latitude: 51.473213, pinkreader: false, lines: 'Piccadilly', zone: '4' },
{ fullname: 'Hounslow West Underground Station', name: 'Hounslow West', mininame: 'Houns...', longitude: -0.386544, latitude: 51.473469, pinkreader: false, lines: 'Piccadilly', zone: '5' },
{ fullname: 'Hoxton Rail Station', name: 'Hoxton', mininame: 'Hoxto...', longitude: -0.075681, latitude: 51.531512, pinkreader: false, lines: 'London Overground', zone: '1+2' },
{ fullname: 'Hyde Park Corner Underground Station', name: 'Hyde Park Corner', mininame: 'Hyde ...', longitude: -0.152441, latitude: 51.503035, pinkreader: false, lines: 'Piccadilly', zone: '1' },
{ fullname: 'Ickenham Underground Station', name: 'Ickenham', mininame: 'Icken...', longitude: -0.442001, latitude: 51.561992, pinkreader: false, lines: 'Metropolitan, Piccadilly', zone: '6' },
{ fullname: 'Imperial Wharf Rail Station', name: 'Imperial Wharf', mininame: 'Imper...', longitude: -0.182823, latitude: 51.474949, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Island Gardens DLR Station', name: 'Island Gardens', mininame: 'Islan...', longitude: -0.010139, latitude: 51.487811, pinkreader: false, lines: 'DLR', zone: '2' },
{ fullname: 'Kennington Underground Station', name: 'Kennington', mininame: 'Kenni...', longitude: -0.105963, latitude: 51.488337, pinkreader: false, lines: 'Northern', zone: '2' },
{ fullname: 'Kensal Green Rail Station', name: 'Kensal Green', mininame: 'Kensa...', longitude: -0.225088, latitude: 51.53054, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Kensal Green Underground Station', name: 'Kensal Green', mininame: 'Kensa...', longitude: -0.225016, latitude: 51.530539, pinkreader: false, lines: 'Bakerloo', zone: '2' },
{ fullname: 'Kensal Rise Rail Station', name: 'Kensal Rise', mininame: 'Kensa...', longitude: -0.219957, latitude: 51.534554, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Kensington (Olympia) Rail Station', name: 'Kensington (Olympia)', mininame: 'Kensi...', longitude: -0.210364, latitude: 51.497899, pinkreader: true, lines: 'London Overground', zone: '2' },
{ fullname: 'Kensington (Olympia) Underground Station', name: 'Kensington (Olympia)', mininame: 'Kensi...', longitude: -0.210015, latitude: 51.497624, pinkreader: false, lines: 'District', zone: '2' },
{ fullname: 'Kentish Town Underground Station', name: 'Kentish Town', mininame: 'Kenti...', longitude: -0.140733, latitude: 51.550312, pinkreader: false, lines: 'Northern', zone: '2' },
{ fullname: 'Kentish Town West Rail Station', name: 'Kentish Town West', mininame: 'Kenti...', longitude: -0.146655, latitude: 51.546548, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Kenton Rail Station', name: 'Kenton', mininame: 'Kento...', longitude: -0.316981, latitude: 51.581802, pinkreader: false, lines: 'London Overground', zone: '4' },
{ fullname: 'Kenton Underground Station', name: 'Kenton', mininame: 'Kento...', longitude: -0.31691, latitude: 51.581756, pinkreader: false, lines: 'Bakerloo', zone: '4' },
{ fullname: 'Kew Gardens Rail Station', name: 'Kew Gardens', mininame: 'Kew G...', longitude: -0.285054, latitude: 51.477073, pinkreader: false, lines: 'London Overground', zone: '3+4' },
{ fullname: 'Kew Gardens Underground Station', name: 'Kew Gardens', mininame: 'Kew G...', longitude: -0.285241, latitude: 51.477058, pinkreader: false, lines: 'District', zone: '3+4' },
{ fullname: 'Kilburn High Road Rail Station', name: 'Kilburn High Road', mininame: 'Kilbu...', longitude: -0.192237, latitude: 51.537277, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Kilburn Park Underground Station', name: 'Kilburn Park', mininame: 'Kilbu...', longitude: -0.194232, latitude: 51.534979, pinkreader: false, lines: 'Bakerloo', zone: '2' },
{ fullname: 'Kilburn Underground Station', name: 'Kilburn', mininame: 'Kilbu...', longitude: -0.204105, latitude: 51.546803, pinkreader: false, lines: 'Jubilee', zone: '2' },
{ fullname: 'King George V DLR Station', name: 'King George V', mininame: 'King ...', longitude: 0.062624, latitude: 51.502003, pinkreader: false, lines: 'DLR', zone: '3' },
{ fullname: 'King&#39;s Cross St. Pancras Underground Station', name: 'King&#39;s Cross St. Pancras', mininame: 'King&...', longitude: -0.123194, latitude: 51.530663, pinkreader: false, lines: 'Circle, Hammersmith & City, Metropolitan, Northern, Piccadilly, Victoria', zone: '1' },
{ fullname: 'Kingsbury Underground Station', name: 'Kingsbury', mininame: 'Kings...', longitude: -0.27879, latitude: 51.584845, pinkreader: false, lines: 'Jubilee', zone: '4' },
{ fullname: 'Knightsbridge Underground Station', name: 'Knightsbridge', mininame: 'Knigh...', longitude: -0.160508, latitude: 51.501669, pinkreader: false, lines: 'Piccadilly', zone: '1' },
{ fullname: 'Ladbroke Grove Underground Station', name: 'Ladbroke Grove', mininame: 'Ladbr...', longitude: -0.210391, latitude: 51.517449, pinkreader: false, lines: 'Circle, Hammersmith & City', zone: '2' },
{ fullname: 'Lambeth North Underground Station', name: 'Lambeth North', mininame: 'Lambe...', longitude: -0.112315, latitude: 51.498808, pinkreader: false, lines: 'Bakerloo', zone: '1' },
{ fullname: 'Lancaster Gate Underground Station', name: 'Lancaster Gate', mininame: 'Lanca...', longitude: -0.175494, latitude: 51.511723, pinkreader: false, lines: 'Central', zone: '1' },
{ fullname: 'Langdon Park DLR Station', name: 'Langdon Park', mininame: 'Langd...', longitude: -0.01415, latitude: 51.515172, pinkreader: false, lines: 'DLR', zone: '2' },
{ fullname: 'Latimer Road Underground Station', name: 'Latimer Road', mininame: 'Latim...', longitude: -0.217799, latitude: 51.513389, pinkreader: false, lines: 'Circle, Hammersmith & City', zone: '2' },
{ fullname: 'Leicester Square Underground Station', name: 'Leicester Square', mininame: 'Leice...', longitude: -0.128426, latitude: 51.511386, pinkreader: false, lines: 'Northern, Piccadilly', zone: '1' },
{ fullname: 'Lewisham DLR Station', name: 'Lewisham', mininame: 'Lewis...', longitude: -0.012874, latitude: 51.464665, pinkreader: false, lines: 'DLR', zone: '2+3' },
{ fullname: 'Leyton Midland Road Rail Station', name: 'Leyton Midland Road', mininame: 'Leyto...', longitude: -0.008051, latitude: 51.569725, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'Leyton Underground Station', name: 'Leyton', mininame: 'Leyto...', longitude: -0.005523, latitude: 51.556589, pinkreader: false, lines: 'Central', zone: '3' },
{ fullname: 'Leytonstone High Road Rail Station', name: 'Leytonstone High Road', mininame: 'Leyto...', longitude: 0.008416, latitude: 51.563554, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'Leytonstone Underground Station', name: 'Leytonstone', mininame: 'Leyto...', longitude: 0.008194, latitude: 51.568324, pinkreader: false, lines: 'Central', zone: '3+4' },
{ fullname: 'Limehouse DLR Station', name: 'Limehouse', mininame: 'Limeh...', longitude: -0.039809, latitude: 51.512393, pinkreader: false, lines: 'DLR', zone: '2' },
{ fullname: 'Liverpool Street Underground Station', name: 'Liverpool Street', mininame: 'Liver...', longitude: -0.083182, latitude: 51.517372, pinkreader: false, lines: 'Central, Circle, Hammersmith & City, Metropolitan', zone: '1' },
{ fullname: 'London Bridge Underground Station', name: 'London Bridge', mininame: 'Londo...', longitude: -0.088873, latitude: 51.505721, pinkreader: false, lines: 'Jubilee, Northern', zone: '1' },
{ fullname: 'London City Airport DLR Station', name: 'London City Airport', mininame: 'Londo...', longitude: 0.048739, latitude: 51.503416, pinkreader: false, lines: 'DLR', zone: '3' },
{ fullname: 'London Euston Rail Station', name: 'London Euston', mininame: 'Londo...', longitude: -0.133924, latitude: 51.528136, pinkreader: false, lines: 'London Overground', zone: '1' },
{ fullname: 'London Fields Rail Station', name: 'London Fields', mininame: 'Londo...', longitude: -0.057753, latitude: 51.541153, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'London Liverpool Street Rail Station', name: 'London Liverpool Street', mininame: 'Londo...', longitude: -0.081426, latitude: 51.517991, pinkreader: false, lines: 'London Overground', zone: '1' },
{ fullname: 'Loughton Underground Station', name: 'Loughton', mininame: 'Lough...', longitude: 0.055476, latitude: 51.641443, pinkreader: false, lines: 'Central', zone: '6' },
{ fullname: 'Maida Vale Underground Station', name: 'Maida Vale', mininame: 'Maida...', longitude: -0.185758, latitude: 51.529777, pinkreader: false, lines: 'Bakerloo', zone: '2' },
{ fullname: 'Manor House Underground Station', name: 'Manor House', mininame: 'Manor...', longitude: -0.096118, latitude: 51.570738, pinkreader: false, lines: 'Piccadilly', zone: '2+3' },
{ fullname: 'Mansion House Underground Station', name: 'Mansion House', mininame: 'Mansi...', longitude: -0.094009, latitude: 51.512117, pinkreader: false, lines: 'Circle, District', zone: '1' },
{ fullname: 'Marble Arch Underground Station', name: 'Marble Arch', mininame: 'Marbl...', longitude: -0.158953, latitude: 51.513424, pinkreader: false, lines: 'Central', zone: '1' },
{ fullname: 'Marylebone Underground Station', name: 'Marylebone', mininame: 'Maryl...', longitude: -0.163207, latitude: 51.522322, pinkreader: false, lines: 'Bakerloo', zone: '1' },
{ fullname: 'Mile End Underground Station', name: 'Mile End', mininame: 'Mile ...', longitude: -0.03364, latitude: 51.525122, pinkreader: false, lines: 'Central, District, Hammersmith & City', zone: '2' },
{ fullname: 'Mill Hill East Underground Station', name: 'Mill Hill East', mininame: 'Mill ...', longitude: -0.209986, latitude: 51.608229, pinkreader: false, lines: 'Northern', zone: '4' },
{ fullname: 'Monument Underground Station', name: 'Monument', mininame: 'Monum...', longitude: -0.085969, latitude: 51.5107, pinkreader: false, lines: 'Circle, District', zone: '1' },
{ fullname: 'Moor Park Underground Station', name: 'Moor Park', mininame: 'Moor ...', longitude: -0.432454, latitude: 51.629845, pinkreader: false, lines: 'Metropolitan', zone: '6+7' },
{ fullname: 'Moorgate Underground Station', name: 'Moorgate', mininame: 'Moorg...', longitude: -0.088322, latitude: 51.518176, pinkreader: false, lines: 'Circle, Hammersmith & City, Metropolitan, Northern', zone: '1' },
{ fullname: 'Morden Underground Station', name: 'Morden', mininame: 'Morde...', longitude: -0.194839, latitude: 51.402142, pinkreader: false, lines: 'Northern', zone: '4' },
{ fullname: 'Mornington Crescent Underground Station', name: 'Mornington Crescent', mininame: 'Morni...', longitude: -0.138789, latitude: 51.534679, pinkreader: false, lines: 'Northern', zone: '2' },
{ fullname: 'Mudchute DLR Station', name: 'Mudchute', mininame: 'Mudch...', longitude: -0.014738, latitude: 51.490704, pinkreader: false, lines: 'DLR', zone: '2' },
{ fullname: 'Neasden Underground Station', name: 'Neasden', mininame: 'Neasd...', longitude: -0.249837, latitude: 51.553986, pinkreader: false, lines: 'Jubilee', zone: '3' },
{ fullname: 'New Cross ELL Rail Station', name: 'New Cross ELL', mininame: 'New C...', longitude: -0.032441, latitude: 51.476344, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'New Cross Gate Rail Station', name: 'New Cross Gate', mininame: 'New C...', longitude: -0.040399, latitude: 51.475128, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Newbury Park Underground Station', name: 'Newbury Park', mininame: 'Newbu...', longitude: 0.090004, latitude: 51.575726, pinkreader: false, lines: 'Central', zone: '4' },
{ fullname: 'North Acton Underground Station', name: 'North Acton', mininame: 'North...', longitude: -0.259755, latitude: 51.523524, pinkreader: false, lines: 'Central', zone: '2+3' },
{ fullname: 'North Ealing Underground Station', name: 'North Ealing', mininame: 'North...', longitude: -0.288868, latitude: 51.517505, pinkreader: false, lines: 'Piccadilly', zone: '3' },
{ fullname: 'North Greenwich Underground Station', name: 'North Greenwich', mininame: 'North...', longitude: 0.004287, latitude: 51.50047, pinkreader: false, lines: 'Jubilee', zone: '2+3' },
{ fullname: 'North Harrow Underground Station', name: 'North Harrow', mininame: 'North...', longitude: -0.362408, latitude: 51.584872, pinkreader: false, lines: 'Metropolitan', zone: '5' },
{ fullname: 'North Wembley Rail Station', name: 'North Wembley', mininame: 'North...', longitude: -0.303984, latitude: 51.562596, pinkreader: false, lines: 'London Overground', zone: '4' },
{ fullname: 'North Wembley Underground Station', name: 'North Wembley', mininame: 'North...', longitude: -0.304, latitude: 51.562551, pinkreader: false, lines: 'Bakerloo', zone: '4' },
{ fullname: 'Northfields Underground Station', name: 'Northfields', mininame: 'North...', longitude: -0.314719, latitude: 51.499319, pinkreader: false, lines: 'Piccadilly', zone: '3' },
{ fullname: 'Northolt Underground Station', name: 'Northolt', mininame: 'North...', longitude: -0.368699, latitude: 51.548236, pinkreader: false, lines: 'Central', zone: '5' },
{ fullname: 'Northwick Park Underground Station', name: 'Northwick Park', mininame: 'North...', longitude: -0.318056, latitude: 51.578481, pinkreader: false, lines: 'Metropolitan', zone: '4' },
{ fullname: 'Northwood Hills Underground Station', name: 'Northwood Hills', mininame: 'North...', longitude: -0.409464, latitude: 51.600572, pinkreader: false, lines: 'Metropolitan', zone: '6' },
{ fullname: 'Northwood Underground Station', name: 'Northwood', mininame: 'North...', longitude: -0.423829, latitude: 51.611053, pinkreader: false, lines: 'Metropolitan', zone: '6' },
{ fullname: 'Norwood Junction Rail Station', name: 'Norwood Junction', mininame: 'Norwo...', longitude: -0.075221, latitude: 51.397019, pinkreader: false, lines: 'London Overground', zone: '4' },
{ fullname: 'Notting Hill Gate Underground Station', name: 'Notting Hill Gate', mininame: 'Notti...', longitude: -0.196104, latitude: 51.509128, pinkreader: false, lines: 'Central, Circle, District', zone: '1+2' },
{ fullname: 'Oakwood Underground Station', name: 'Oakwood', mininame: 'Oakwo...', longitude: -0.132182, latitude: 51.647726, pinkreader: false, lines: 'Piccadilly', zone: '5' },
{ fullname: 'Old Street Underground Station', name: 'Old Street', mininame: 'Old S...', longitude: -0.08777, latitude: 51.525864, pinkreader: false, lines: 'Northern', zone: '1' },
{ fullname: 'Osterley Underground Station', name: 'Osterley', mininame: 'Oster...', longitude: -0.352224, latitude: 51.481274, pinkreader: false, lines: 'Piccadilly', zone: '4' },
{ fullname: 'Oval Underground Station', name: 'Oval', mininame: 'Oval ...', longitude: -0.112439, latitude: 51.48185, pinkreader: false, lines: 'Northern', zone: '2' },
{ fullname: 'Oxford Circus Underground Station', name: 'Oxford Circus', mininame: 'Oxfor...', longitude: -0.141903, latitude: 51.515224, pinkreader: false, lines: 'Bakerloo, Central, Victoria', zone: '1' },
{ fullname: 'Paddington (H&C Line)-Underground', name: 'Paddington (H&C Line)-Underground', mininame: 'Paddi...', longitude: -0.178306, latitude: 51.518187, pinkreader: false, lines: 'Circle, Hammersmith & City', zone: '1' },
{ fullname: 'Paddington Underground Station', name: 'Paddington', mininame: 'Paddi...', longitude: -0.175689, latitude: 51.516581, pinkreader: false, lines: 'Bakerloo, Circle, District', zone: '1' },
{ fullname: 'Park Royal Underground Station', name: 'Park Royal', mininame: 'Park ...', longitude: -0.284341, latitude: 51.527123, pinkreader: false, lines: 'Piccadilly', zone: '3' },
{ fullname: 'Parsons Green Underground Station', name: 'Parsons Green', mininame: 'Parso...', longitude: -0.20117, latitude: 51.475277, pinkreader: false, lines: 'District', zone: '2' },
{ fullname: 'Peckham Rye Rail Station', name: 'Peckham Rye', mininame: 'Peckh...', longitude: -0.069414, latitude: 51.470034, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Penge West Rail Station', name: 'Penge West', mininame: 'Penge...', longitude: -0.06084, latitude: 51.417555, pinkreader: false, lines: 'London Overground', zone: '4' },
{ fullname: 'Perivale Underground Station', name: 'Perivale', mininame: 'Periv...', longitude: -0.323446, latitude: 51.536717, pinkreader: false, lines: 'Central', zone: '4' },
{ fullname: 'Piccadilly Circus Underground Station', name: 'Piccadilly Circus', mininame: 'Picca...', longitude: -0.133798, latitude: 51.51005, pinkreader: false, lines: 'Bakerloo, Piccadilly', zone: '1' },
{ fullname: 'Pimlico Underground Station', name: 'Pimlico', mininame: 'Pimli...', longitude: -0.133761, latitude: 51.489097, pinkreader: false, lines: 'Victoria', zone: '1' },
{ fullname: 'Pinner Underground Station', name: 'Pinner', mininame: 'Pinne...', longitude: -0.381161, latitude: 51.592901, pinkreader: false, lines: 'Metropolitan', zone: '5' },
{ fullname: 'Plaistow Underground Station', name: 'Plaistow', mininame: 'Plais...', longitude: 0.017451, latitude: 51.531341, pinkreader: false, lines: 'District, Hammersmith & City', zone: '3' },
{ fullname: 'Pontoon Dock DLR Station', name: 'Pontoon Dock', mininame: 'Ponto...', longitude: 0.032115, latitude: 51.502212, pinkreader: false, lines: 'DLR', zone: '3' },
{ fullname: 'Poplar DLR Station', name: 'Poplar', mininame: 'Popla...', longitude: -0.017384, latitude: 51.507744, pinkreader: false, lines: 'DLR', zone: '2' },
{ fullname: 'Preston Road Underground Station', name: 'Preston Road', mininame: 'Prest...', longitude: -0.295107, latitude: 51.571972, pinkreader: false, lines: 'Metropolitan', zone: '4' },
{ fullname: 'Prince Regent DLR Station', name: 'Prince Regent', mininame: 'Princ...', longitude: 0.034158, latitude: 51.509263, pinkreader: false, lines: 'DLR', zone: '3' },
{ fullname: 'Pudding Mill Lane DLR Station', name: 'Pudding Mill Lane', mininame: 'Puddi...', longitude: -0.012755, latitude: 51.534302, pinkreader: false, lines: 'DLR', zone: '2+3' },
{ fullname: 'Putney Bridge Underground Station', name: 'Putney Bridge', mininame: 'Putne...', longitude: -0.208731, latitude: 51.468262, pinkreader: false, lines: 'District', zone: '2' },
{ fullname: 'Queen&#39;s Park Underground Station', name: 'Queen&#39;s Park', mininame: 'Queen...', longitude: -0.204574, latitude: 51.534158, pinkreader: false, lines: 'Bakerloo', zone: '2' },
{ fullname: 'Queens Park (London) Rail Station', name: 'Queens Park (London)', mininame: 'Queen...', longitude: -0.204985, latitude: 51.533966, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Queens Road Peckham Rail Station', name: 'Queens Road Peckham', mininame: 'Queen...', longitude: -0.057313, latitude: 51.473566, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Queensbury Underground Station', name: 'Queensbury', mininame: 'Queen...', longitude: -0.286219, latitude: 51.594188, pinkreader: false, lines: 'Jubilee', zone: '4' },
{ fullname: 'Queensway Underground Station', name: 'Queensway', mininame: 'Queen...', longitude: -0.187152, latitude: 51.510312, pinkreader: false, lines: 'Central', zone: '1' },
{ fullname: 'Ravenscourt Park Underground Station', name: 'Ravenscourt Park', mininame: 'Raven...', longitude: -0.235881, latitude: 51.494122, pinkreader: false, lines: 'District, Piccadilly', zone: '2' },
{ fullname: 'Rayners Lane Underground Station', name: 'Rayners Lane', mininame: 'Rayne...', longitude: -0.371127, latitude: 51.575147, pinkreader: true, lines: 'Metropolitan, Piccadilly', zone: '5' },
{ fullname: 'Rectory Road Rail Station', name: 'Rectory Road', mininame: 'Recto...', longitude: -0.068267, latitude: 51.558502, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Redbridge Underground Station', name: 'Redbridge', mininame: 'Redbr...', longitude: 0.04536, latitude: 51.576243, pinkreader: false, lines: 'Central', zone: '4' },
{ fullname: 'Regent&#39;s Park Underground Station', name: 'Regent&#39;s Park', mininame: 'Regen...', longitude: -0.146444, latitude: 51.523344, pinkreader: false, lines: 'Bakerloo', zone: '1' },
{ fullname: 'Richmond (London) Rail Station', name: 'Richmond (London)', mininame: 'Richm...', longitude: -0.301558, latitude: 51.463061, pinkreader: true, lines: 'London Overground', zone: '4' },
{ fullname: 'Richmond Underground Station', name: 'Richmond', mininame: 'Richm...', longitude: -0.301336, latitude: 51.463237, pinkreader: false, lines: 'District', zone: '4' },
{ fullname: 'Rickmansworth Underground Station', name: 'Rickmansworth', mininame: 'Rickm...', longitude: -0.473703, latitude: 51.640207, pinkreader: false, lines: 'Metropolitan', zone: '7' },
{ fullname: 'Roding Valley Underground Station', name: 'Roding Valley', mininame: 'Rodin...', longitude: 0.043647, latitude: 51.617199, pinkreader: false, lines: 'Central', zone: '4' },
{ fullname: 'Romford Rail Station', name: 'Romford', mininame: 'Romfo...', longitude: 0.183237, latitude: 51.574829, pinkreader: false, lines: 'London Overground', zone: '6' },
{ fullname: 'Rotherhithe Rail Station', name: 'Rotherhithe', mininame: 'Rothe...', longitude: -0.052048, latitude: 51.500817, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Royal Albert DLR Station', name: 'Royal Albert', mininame: 'Royal...', longitude: 0.045935, latitude: 51.508357, pinkreader: false, lines: 'DLR', zone: '3' },
{ fullname: 'Royal Oak Underground Station', name: 'Royal Oak', mininame: 'Royal...', longitude: -0.188748, latitude: 51.519113, pinkreader: false, lines: 'Circle, Hammersmith & City', zone: '2' },
{ fullname: 'Royal Victoria DLR Station', name: 'Royal Victoria', mininame: 'Royal...', longitude: 0.018497, latitude: 51.509336, pinkreader: false, lines: 'DLR', zone: '3' },
{ fullname: 'Ruislip Gardens Underground Station', name: 'Ruislip Gardens', mininame: 'Ruisl...', longitude: -0.41071, latitude: 51.560736, pinkreader: false, lines: 'Central', zone: '5' },
{ fullname: 'Ruislip Manor Underground Station', name: 'Ruislip Manor', mininame: 'Ruisl...', longitude: -0.412973, latitude: 51.573202, pinkreader: false, lines: 'Metropolitan, Piccadilly', zone: '6' },
{ fullname: 'Ruislip Underground Station', name: 'Ruislip', mininame: 'Ruisl...', longitude: -0.421898, latitude: 51.571354, pinkreader: false, lines: 'Metropolitan, Piccadilly', zone: '6' },
{ fullname: 'Russell Square Underground Station', name: 'Russell Square', mininame: 'Russe...', longitude: -0.124285, latitude: 51.523073, pinkreader: false, lines: 'Piccadilly', zone: '1' },
{ fullname: 'Seven Sisters Rail Station', name: 'Seven Sisters', mininame: 'Seven...', longitude: -0.07527, latitude: 51.582268, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'Seven Sisters Underground Station', name: 'Seven Sisters', mininame: 'Seven...', longitude: -0.072584, latitude: 51.58333, pinkreader: false, lines: 'Victoria', zone: '3' },
{ fullname: 'Shadwell DLR Station', name: 'Shadwell', mininame: 'Shadw...', longitude: -0.056643, latitude: 51.511693, pinkreader: false, lines: 'DLR', zone: '2' },
{ fullname: 'Shadwell Rail Station', name: 'Shadwell', mininame: 'Shadw...', longitude: -0.056934, latitude: 51.511284, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Shepherd&#39;s Bush (Central) Underground Station', name: 'Shepherd&#39;s Bush (Central)', mininame: 'Sheph...', longitude: -0.218813, latitude: 51.504376, pinkreader: false, lines: 'Central', zone: '2' },
{ fullname: 'Shepherd&#39;s Bush Market Underground Station', name: 'Shepherd&#39;s Bush Market', mininame: 'Sheph...', longitude: -0.226375, latitude: 51.505579, pinkreader: false, lines: 'Circle, Hammersmith & City', zone: '2' },
{ fullname: 'Shepherds Bush Rail Station', name: 'Shepherds Bush', mininame: 'Sheph...', longitude: -0.217654, latitude: 51.505285, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Shoreditch High Street Rail Station', name: 'Shoreditch High Street', mininame: 'Shore...', longitude: -0.075246, latitude: 51.523375, pinkreader: false, lines: 'London Overground', zone: '1' },
{ fullname: 'Silver Street Rail Station', name: 'Silver Street', mininame: 'Silve...', longitude: -0.06724, latitude: 51.614688, pinkreader: false, lines: 'London Overground', zone: '4' },
{ fullname: 'Sloane Square Underground Station', name: 'Sloane Square', mininame: 'Sloan...', longitude: -0.156377, latitude: 51.49227, pinkreader: false, lines: 'Circle, District', zone: '1' },
{ fullname: 'Snaresbrook Underground Station', name: 'Snaresbrook', mininame: 'Snare...', longitude: 0.02144, latitude: 51.580678, pinkreader: false, lines: 'Central', zone: '4' },
{ fullname: 'South Acton Rail Station', name: 'South Acton', mininame: 'South...', longitude: -0.270157, latitude: 51.499695, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'South Ealing Underground Station', name: 'South Ealing', mininame: 'South...', longitude: -0.307424, latitude: 51.501003, pinkreader: false, lines: 'Piccadilly', zone: '3' },
{ fullname: 'South Hampstead Rail Station', name: 'South Hampstead', mininame: 'South...', longitude: -0.178878, latitude: 51.541432, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'South Harrow Underground Station', name: 'South Harrow', mininame: 'South...', longitude: -0.352492, latitude: 51.564888, pinkreader: false, lines: 'Piccadilly', zone: '5' },
{ fullname: 'South Kensington Underground Station', name: 'South Kensington', mininame: 'South...', longitude: -0.174138, latitude: 51.494094, pinkreader: false, lines: 'Circle, District, Piccadilly', zone: '1' },
{ fullname: 'South Kenton Rail Station', name: 'South Kenton', mininame: 'South...', longitude: -0.308462, latitude: 51.570214, pinkreader: false, lines: 'London Overground', zone: '4' },
{ fullname: 'South Kenton Underground Station', name: 'South Kenton', mininame: 'South...', longitude: -0.308433, latitude: 51.570232, pinkreader: false, lines: 'Bakerloo', zone: '4' },
{ fullname: 'South Quay DLR Station', name: 'South Quay', mininame: 'South...', longitude: -0.016133, latitude: 51.500053, pinkreader: false, lines: 'DLR', zone: '2' },
{ fullname: 'South Ruislip Underground Station', name: 'South Ruislip', mininame: 'South...', longitude: -0.398915, latitude: 51.556853, pinkreader: false, lines: 'Central', zone: '5' },
{ fullname: 'South Tottenham Rail Station', name: 'South Tottenham', mininame: 'South...', longitude: -0.072103, latitude: 51.580372, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'South Wimbledon Underground Station', name: 'South Wimbledon', mininame: 'South...', longitude: -0.192005, latitude: 51.415309, pinkreader: false, lines: 'Northern', zone: '3+4' },
{ fullname: 'South Woodford Underground Station', name: 'South Woodford', mininame: 'South...', longitude: 0.027338, latitude: 51.591907, pinkreader: false, lines: 'Central', zone: '4' },
{ fullname: 'Southbury Rail Station', name: 'Southbury', mininame: 'South...', longitude: -0.052437, latitude: 51.648705, pinkreader: false, lines: 'London Overground', zone: '5' },
{ fullname: 'Southfields Underground Station', name: 'Southfields', mininame: 'South...', longitude: -0.206602, latitude: 51.445073, pinkreader: false, lines: 'District', zone: '3' },
{ fullname: 'Southgate Underground Station', name: 'Southgate', mininame: 'South...', longitude: -0.127816, latitude: 51.632315, pinkreader: false, lines: 'Piccadilly', zone: '4' },
{ fullname: 'Southwark Underground Station', name: 'Southwark', mininame: 'South...', longitude: -0.10494, latitude: 51.503976, pinkreader: false, lines: 'Jubilee', zone: '1' },
{ fullname: 'St James Street (London) Rail Station', name: 'St James Street (London)', mininame: 'St Ja...', longitude: -0.032918, latitude: 51.580981, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'St. James&#39;s Park Underground Station', name: 'St. James&#39;s Park', mininame: 'St. J...', longitude: -0.133608, latitude: 51.499544, pinkreader: false, lines: 'Circle, District', zone: '1' },
{ fullname: 'St. John&#39;s Wood Underground Station', name: 'St. John&#39;s Wood', mininame: 'St. J...', longitude: -0.173948, latitude: 51.534521, pinkreader: false, lines: 'Jubilee', zone: '2' },
{ fullname: 'St. Paul&#39;s Underground Station', name: 'St. Paul&#39;s', mininame: 'St. P...', longitude: -0.097567, latitude: 51.514936, pinkreader: false, lines: 'Central', zone: '1' },
{ fullname: 'Stamford Brook Underground Station', name: 'Stamford Brook', mininame: 'Stamf...', longitude: -0.245704, latitude: 51.494917, pinkreader: false, lines: 'District, Piccadilly', zone: '2' },
{ fullname: 'Stamford Hill Rail Station', name: 'Stamford Hill', mininame: 'Stamf...', longitude: -0.076682, latitude: 51.574467, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'Stanmore Underground Station', name: 'Stanmore', mininame: 'Stanm...', longitude: -0.303266, latitude: 51.619839, pinkreader: false, lines: 'Jubilee', zone: '5' },
{ fullname: 'Star Lane DLR Station', name: 'Star Lane', mininame: 'Star ...', longitude: 0.004156, latitude: 51.520786, pinkreader: false, lines: 'DLR', zone: '2/3' },
{ fullname: 'Stepney Green Underground Station', name: 'Stepney Green', mininame: 'Stepn...', longitude: -0.046596, latitude: 51.521858, pinkreader: false, lines: 'District, Hammersmith & City', zone: '2' },
{ fullname: 'Stockwell Underground Station', name: 'Stockwell', mininame: 'Stock...', longitude: -0.122644, latitude: 51.472184, pinkreader: false, lines: 'Northern, Victoria', zone: '2' },
{ fullname: 'Stoke Newington Rail Station', name: 'Stoke Newington', mininame: 'Stoke...', longitude: -0.072887, latitude: 51.565233, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Stonebridge Park Rail Station', name: 'Stonebridge Park', mininame: 'Stone...', longitude: -0.275828, latitude: 51.544111, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'Stonebridge Park Underground Station', name: 'Stonebridge Park', mininame: 'Stone...', longitude: -0.275892, latitude: 51.543959, pinkreader: false, lines: 'Bakerloo', zone: '3' },
{ fullname: 'Stratford (London) Rail Station', name: 'Stratford (London)', mininame: 'Strat...', longitude: -0.003397, latitude: 51.541895, pinkreader: false, lines: 'London Overground', zone: '2/3' },
{ fullname: 'Stratford DLR Station', name: 'Stratford', mininame: 'Strat...', longitude: -0.003287, latitude: 51.541758, pinkreader: false, lines: 'DLR', zone: '2/3' },
{ fullname: 'Stratford High Street DLR Station', name: 'Stratford High Street', mininame: 'Strat...', longitude: -0.001078, latitude: 51.538196, pinkreader: false, lines: 'DLR', zone: '2/3' },
{ fullname: 'Stratford International DLR Station', name: 'Stratford International', mininame: 'Strat...', longitude: -0.009638, latitude: 51.545265, pinkreader: false, lines: 'DLR', zone: '2/3' },
{ fullname: 'Stratford Underground Station', name: 'Stratford', mininame: 'Strat...', longitude: -0.003458, latitude: 51.541806, pinkreader: false, lines: 'Central, Jubilee', zone: '2/3' },
{ fullname: 'Sudbury Hill Underground Station', name: 'Sudbury Hill', mininame: 'Sudbu...', longitude: -0.336435, latitude: 51.556946, pinkreader: false, lines: 'Piccadilly', zone: '4' },
{ fullname: 'Sudbury Town Underground Station', name: 'Sudbury Town', mininame: 'Sudbu...', longitude: -0.315745, latitude: 51.550815, pinkreader: false, lines: 'Piccadilly', zone: '4' },
{ fullname: 'Surrey Quays Rail Station', name: 'Surrey Quays', mininame: 'Surre...', longitude: -0.047519, latitude: 51.493196, pinkreader: true, lines: 'London Overground', zone: '2' },
{ fullname: 'Swiss Cottage Underground Station', name: 'Swiss Cottage', mininame: 'Swiss...', longitude: -0.174894, latitude: 51.543681, pinkreader: false, lines: 'Jubilee', zone: '2' },
{ fullname: 'Sydenham Rail Station', name: 'Sydenham', mininame: 'Syden...', longitude: -0.054244, latitude: 51.427248, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'Temple Underground Station', name: 'Temple', mininame: 'Templ...', longitude: -0.11426, latitude: 51.511006, pinkreader: false, lines: 'Circle, District', zone: '1' },
{ fullname: 'Theobalds Grove Rail Station', name: 'Theobalds Grove', mininame: 'Theob...', longitude: -0.034831, latitude: 51.692457, pinkreader: false, lines: 'London Overground', zone: '7' },
{ fullname: 'Theydon Bois Underground Station', name: 'Theydon Bois', mininame: 'Theyd...', longitude: 0.103085, latitude: 51.671759, pinkreader: false, lines: 'Central', zone: '6' },
{ fullname: 'Tooting Bec Underground Station', name: 'Tooting Bec', mininame: 'Tooti...', longitude: -0.159736, latitude: 51.435678, pinkreader: false, lines: 'Northern', zone: '3' },
{ fullname: 'Tooting Broadway Underground Station', name: 'Tooting Broadway', mininame: 'Tooti...', longitude: -0.168374, latitude: 51.42763, pinkreader: false, lines: 'Northern', zone: '3' },
{ fullname: 'Tottenham Court Road Underground Station', name: 'Tottenham Court Road', mininame: 'Totte...', longitude: -0.13041, latitude: 51.516426, pinkreader: false, lines: 'Central, Northern', zone: '1' },
{ fullname: 'Tottenham Hale Underground Station', name: 'Tottenham Hale', mininame: 'Totte...', longitude: -0.060241, latitude: 51.588108, pinkreader: false, lines: 'Victoria', zone: '3' },
{ fullname: 'Totteridge & Whetstone Underground Station', name: 'Totteridge & Whetstone', mininame: 'Totte...', longitude: -0.17921, latitude: 51.630597, pinkreader: false, lines: 'Northern', zone: '4' },
{ fullname: 'Tower Gateway DLR Station', name: 'Tower Gateway', mininame: 'Tower...', longitude: -0.074818, latitude: 51.510617, pinkreader: false, lines: 'DLR', zone: '1' },
{ fullname: 'Tower Hill Underground Station', name: 'Tower Hill', mininame: 'Tower...', longitude: -0.076546, latitude: 51.509971, pinkreader: false, lines: 'Circle, District', zone: '1' },
{ fullname: 'Tufnell Park Underground Station', name: 'Tufnell Park', mininame: 'Tufne...', longitude: -0.138433, latitude: 51.556822, pinkreader: false, lines: 'Northern', zone: '2' },
{ fullname: 'Turkey Street Rail Station', name: 'Turkey Street', mininame: 'Turke...', longitude: -0.047217, latitude: 51.672628, pinkreader: false, lines: 'London Overground', zone: '6' },
{ fullname: 'Turnham Green Underground Station', name: 'Turnham Green', mininame: 'Turnh...', longitude: -0.254555, latitude: 51.495148, pinkreader: false, lines: 'District, Piccadilly', zone: '2' },
{ fullname: 'Turnpike Lane Underground Station', name: 'Turnpike Lane', mininame: 'Turnp...', longitude: -0.102953, latitude: 51.590272, pinkreader: false, lines: 'Piccadilly', zone: '3' },
{ fullname: 'Upminster Bridge Underground Station', name: 'Upminster Bridge', mininame: 'Upmin...', longitude: 0.235809, latitude: 51.55856, pinkreader: false, lines: 'District', zone: '6' },
{ fullname: 'Upminster Rail Station', name: 'Upminster', mininame: 'Upmin...', longitude: 0.25088, latitude: 51.559018, pinkreader: false, lines: 'London Overground', zone: '6' },
{ fullname: 'Upminster Underground Station', name: 'Upminster', mininame: 'Upmin...', longitude: 0.250882, latitude: 51.559063, pinkreader: false, lines: 'District', zone: '6' },
{ fullname: 'Upney Underground Station', name: 'Upney', mininame: 'Upney...', longitude: 0.10153, latitude: 51.538372, pinkreader: false, lines: 'District', zone: '4' },
{ fullname: 'Upper Holloway Rail Station', name: 'Upper Holloway', mininame: 'Upper...', longitude: -0.129513, latitude: 51.563631, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Upton Park Underground Station', name: 'Upton Park', mininame: 'Upton...', longitude: 0.035263, latitude: 51.53534, pinkreader: false, lines: 'District, Hammersmith & City', zone: '3' },
{ fullname: 'Uxbridge Underground Station', name: 'Uxbridge', mininame: 'Uxbri...', longitude: -0.477949, latitude: 51.546565, pinkreader: false, lines: 'Metropolitan, Piccadilly', zone: '6' },
{ fullname: 'Vauxhall Underground Station', name: 'Vauxhall', mininame: 'Vauxh...', longitude: -0.124204, latitude: 51.485743, pinkreader: false, lines: 'Victoria', zone: '1+2' },
{ fullname: 'Victoria Underground Station', name: 'Victoria', mininame: 'Victo...', longitude: -0.143102, latitude: 51.496359, pinkreader: false, lines: 'Circle, District, Victoria', zone: '1' },
{ fullname: 'Walthamstow Central Rail Station', name: 'Walthamstow Central', mininame: 'Walth...', longitude: -0.019815, latitude: 51.582919, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'Walthamstow Central Underground Station', name: 'Walthamstow Central', mininame: 'Walth...', longitude: -0.019885, latitude: 51.582965, pinkreader: false, lines: 'Victoria', zone: '3' },
{ fullname: 'Walthamstow Queens Road Rail Station', name: 'Walthamstow Queens Road', mininame: 'Walth...', longitude: -0.023846, latitude: 51.581503, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'Wandsworth Road Rail Station', name: 'Wandsworth Road', mininame: 'Wands...', longitude: -0.13852, latitude: 51.470216, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Wanstead Park Rail Station', name: 'Wanstead Park', mininame: 'Wanst...', longitude: 0.026213, latitude: 51.551693, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'Wanstead Underground Station', name: 'Wanstead', mininame: 'Wanst...', longitude: 0.028527, latitude: 51.575501, pinkreader: false, lines: 'Central', zone: '4' },
{ fullname: 'Wapping Rail Station', name: 'Wapping', mininame: 'Wappi...', longitude: -0.055931, latitude: 51.504388, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'Warren Street Underground Station', name: 'Warren Street', mininame: 'Warre...', longitude: -0.138321, latitude: 51.524951, pinkreader: false, lines: 'Northern, Victoria', zone: '1' },
{ fullname: 'Warwick Avenue Underground Station', name: 'Warwick Avenue', mininame: 'Warwi...', longitude: -0.183783, latitude: 51.523263, pinkreader: false, lines: 'Bakerloo', zone: '2' },
{ fullname: 'Waterloo Underground Station', name: 'Waterloo', mininame: 'Water...', longitude: -0.11478, latitude: 51.503299, pinkreader: false, lines: 'Bakerloo, Jubilee, Northern, Waterloo & City', zone: '1' },
{ fullname: 'Wembley Central Rail Station', name: 'Wembley Central', mininame: 'Wembl...', longitude: -0.296433, latitude: 51.552325, pinkreader: false, lines: 'London Overground', zone: '4' },
{ fullname: 'Wembley Central Underground Station', name: 'Wembley Central', mininame: 'Wembl...', longitude: -0.296852, latitude: 51.552304, pinkreader: false, lines: 'Bakerloo', zone: '4' },
{ fullname: 'Wembley Park Underground Station', name: 'Wembley Park', mininame: 'Wembl...', longitude: -0.279262, latitude: 51.563198, pinkreader: false, lines: 'Jubilee, Metropolitan', zone: '4' },
{ fullname: 'West Acton Underground Station', name: 'West Acton', mininame: 'West ...', longitude: -0.28098, latitude: 51.518001, pinkreader: false, lines: 'Central', zone: '3' },
{ fullname: 'West Brompton Rail Station', name: 'West Brompton', mininame: 'West ...', longitude: -0.195593, latitude: 51.487061, pinkreader: true, lines: 'London Overground', zone: '2' },
{ fullname: 'West Brompton Underground Station', name: 'West Brompton', mininame: 'West ...', longitude: -0.195599, latitude: 51.487268, pinkreader: false, lines: 'District', zone: '2' },
{ fullname: 'West Croydon Rail Station', name: 'West Croydon', mininame: 'West ...', longitude: -0.102585, latitude: 51.378428, pinkreader: false, lines: 'London Overground', zone: '5' },
{ fullname: 'West Finchley Underground Station', name: 'West Finchley', mininame: 'West ...', longitude: -0.188362, latitude: 51.609426, pinkreader: false, lines: 'Northern', zone: '4' },
{ fullname: 'West Ham DLR Station', name: 'West Ham', mininame: 'West ...', longitude: 0.004482, latitude: 51.527894, pinkreader: false, lines: 'DLR', zone: '2/3' },
{ fullname: 'West Ham Underground Station', name: 'West Ham', mininame: 'West ...', longitude: 0.005055, latitude: 51.528136, pinkreader: false, lines: 'District, Hammersmith & City, Jubilee', zone: '2/3' },
{ fullname: 'West Hampstead Rail Station', name: 'West Hampstead', mininame: 'West ...', longitude: -0.191185, latitude: 51.547468, pinkreader: false, lines: 'London Overground', zone: '2' },
{ fullname: 'West Hampstead Underground Station', name: 'West Hampstead', mininame: 'West ...', longitude: -0.191059, latitude: 51.546638, pinkreader: false, lines: 'Jubilee', zone: '2' },
{ fullname: 'West Harrow Underground Station', name: 'West Harrow', mininame: 'West ...', longitude: -0.3534, latitude: 51.57971, pinkreader: false, lines: 'Metropolitan', zone: '5' },
{ fullname: 'West India Quay DLR Station', name: 'West India Quay', mininame: 'West ...', longitude: -0.020311, latitude: 51.50703, pinkreader: false, lines: 'DLR', zone: '2' },
{ fullname: 'West Kensington Underground Station', name: 'West Kensington', mininame: 'West ...', longitude: -0.206636, latitude: 51.490459, pinkreader: false, lines: 'District', zone: '2' },
{ fullname: 'West Ruislip Underground Station', name: 'West Ruislip', mininame: 'West ...', longitude: -0.437886, latitude: 51.569688, pinkreader: false, lines: 'Central', zone: '6' },
{ fullname: 'West Silvertown DLR Station', name: 'West Silvertown', mininame: 'West ...', longitude: 0.02246, latitude: 51.502838, pinkreader: false, lines: 'DLR', zone: '3' },
{ fullname: 'Westbourne Park Underground Station', name: 'Westbourne Park', mininame: 'Westb...', longitude: -0.201065, latitude: 51.52111, pinkreader: false, lines: 'Circle, Hammersmith & City', zone: '2' },
{ fullname: 'Westferry DLR Station', name: 'Westferry', mininame: 'Westf...', longitude: -0.02675, latitude: 51.509431, pinkreader: false, lines: 'DLR', zone: '2' },
{ fullname: 'Westminster Underground Station', name: 'Westminster', mininame: 'Westm...', longitude: -0.124861, latitude: 51.50132, pinkreader: false, lines: 'Circle, District, Jubilee', zone: '1' },
{ fullname: 'White City Underground Station', name: 'White City', mininame: 'White...', longitude: -0.224297, latitude: 51.511959, pinkreader: false, lines: 'Central', zone: '2' },
{ fullname: 'White Hart Lane Rail Station', name: 'White Hart Lane', mininame: 'White...', longitude: -0.070914, latitude: 51.605037, pinkreader: false, lines: 'London Overground', zone: '3' },
{ fullname: 'Whitechapel Rail Station', name: 'Whitechapel', mininame: 'White...', longitude: -0.059757, latitude: 51.519469, pinkreader: true, lines: 'London Overground', zone: '2' },
{ fullname: 'Whitechapel Underground Station', name: 'Whitechapel', mininame: 'White...', longitude: -0.059971, latitude: 51.519518, pinkreader: false, lines: 'District, Hammersmith & City', zone: '2' },
{ fullname: 'Willesden Green Underground Station', name: 'Willesden Green', mininame: 'Wille...', longitude: -0.221537, latitude: 51.549146, pinkreader: false, lines: 'Jubilee, Metropolitan', zone: '2+3' },
{ fullname: 'Willesden Junction Rail Station', name: 'Willesden Junction', mininame: 'Wille...', longitude: -0.244548, latitude: 51.532497, pinkreader: true, lines: 'London Overground', zone: '2+3' },
{ fullname: 'Willesden Junction Underground Station', name: 'Willesden Junction', mininame: 'Wille...', longitude: -0.244283, latitude: 51.532259, pinkreader: false, lines: 'Bakerloo', zone: '2+3' },
{ fullname: 'Wimbledon Park Underground Station', name: 'Wimbledon Park', mininame: 'Wimbl...', longitude: -0.199719, latitude: 51.434573, pinkreader: false, lines: 'District', zone: '3' },
{ fullname: 'Wimbledon Underground Station', name: 'Wimbledon', mininame: 'Wimbl...', longitude: -0.206573, latitude: 51.421207, pinkreader: true, lines: 'District', zone: '3' },
{ fullname: 'Wood Green Underground Station', name: 'Wood Green', mininame: 'Wood ...', longitude: -0.109886, latitude: 51.597479, pinkreader: false, lines: 'Piccadilly', zone: '3' },
{ fullname: 'Wood Lane Underground Station', name: 'Wood Lane', mininame: 'Wood ...', longitude: -0.22453, latitude: 51.509669, pinkreader: false, lines: 'Circle, Hammersmith & City', zone: '2' },
{ fullname: 'Wood Street Rail Station', name: 'Wood Street', mininame: 'Wood ...', longitude: -0.002405, latitude: 51.58658, pinkreader: false, lines: 'London Overground', zone: '4' },
{ fullname: 'Woodford Underground Station', name: 'Woodford', mininame: 'Woodf...', longitude: 0.03397, latitude: 51.606899, pinkreader: false, lines: 'Central', zone: '4' },
{ fullname: 'Woodgrange Park Rail Station', name: 'Woodgrange Park', mininame: 'Woodg...', longitude: 0.044423, latitude: 51.549264, pinkreader: false, lines: 'London Overground', zone: '3+4' },
{ fullname: 'Woodside Park Underground Station', name: 'Woodside Park', mininame: 'Woods...', longitude: -0.18542, latitude: 51.618014, pinkreader: false, lines: 'Northern', zone: '4' },
{ fullname: 'Woolwich Arsenal DLR Station', name: 'Woolwich Arsenal', mininame: 'Woolw...', longitude: 0.069127, latitude: 51.490009, pinkreader: false, lines: 'DLR', zone: '4' },
];